CREATE TABLE IF NOT EXISTS `pdrb_pengeluaran_td_2010_adh_berlaku` ( 
 `id` int(11) NOT NULL AUTO_INCREMENT, 
 `a` double, 
 `b` double,
 `c` double,
 `d` double,
 `e` double,
 `f` double,
 `g` double,
 `h` double,
 `i` double,
 `j` double,
 `k` double,
 `l` double,
 `m` double,
 `o` double,
 `p` double,
 `q` double,
 `r` double,
 `pdrb` double,
 `pdrb_tanpa_migas` double,
 `triwulan` smallint(6),
 `tahun` smallint(6),
 `created_at` int(11),
 `updated_at` int(11),
 PRIMARY KEY (`id`) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `pdrb_pengeluaran_td_2010_adh_konstan` ( 
 `id` int(11) NOT NULL AUTO_INCREMENT, 
  `a` double, 
 `b` double,
 `c` double,
 `d` double,
 `e` double,
 `f` double,
 `g` double,
 `h` double,
 `i` double,
 `j` double,
 `k` double,
 `l` double,
 `m` double,
 `o` double,
 `p` double,
 `q` double,
 `r` double,
 `pdrb` double,
 `pdrb_tanpa_migas` double,
 `triwulan` smallint(6),
 `tahun` smallint(6),
 `created_at` int(11),
 `updated_at` int(11),
 PRIMARY KEY (`id`) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `distribusi_pdrb_pengeluaran_td_2010_adh_berlaku` ( 
 `id` int(11) NOT NULL AUTO_INCREMENT, 
  `a` double, 
 `b` double,
 `c` double,
 `d` double,
 `e` double,
 `f` double,
 `g` double,
 `h` double,
 `i` double,
 `j` double,
 `k` double,
 `l` double,
 `m` double,
 `o` double,
 `p` double,
 `q` double,
 `r` double,
 `pdrb` double,
 `pdrb_tanpa_migas` double,
 `triwulan` smallint(6),
 `tahun` smallint(6),
 `created_at` int(11),
 `updated_at` int(11),
 PRIMARY KEY (`id`) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `pertumbuhan_pdrb_pengeluaran_td_2010_adh_konstan_qtoq` ( 
 `id` int(11) NOT NULL AUTO_INCREMENT, 
 `a` double, 
 `b` double,
 `c` double,
 `d` double,
 `e` double,
 `f` double,
 `g` double,
 `h` double,
 `i` double,
 `j` double,
 `k` double,
 `l` double,
 `m` double,
 `o` double,
 `p` double,
 `q` double,
 `r` double,
 `pdrb` double,
 `pdrb_tanpa_migas` double,
 `triwulan` smallint(6),
 `tahun` smallint(6),
 `created_at` int(11),
 `updated_at` int(11),
 PRIMARY KEY (`id`) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `pertumbuhan_pdrb_pengeluaran_td_2010_adh_konstan_ytoy` ( 
 `id` int(11) NOT NULL AUTO_INCREMENT, 
  `a` double, 
 `b` double,
 `c` double,
 `d` double,
 `e` double,
 `f` double,
 `g` double,
 `h` double,
 `i` double,
 `j` double,
 `k` double,
 `l` double,
 `m` double,
 `o` double,
 `p` double,
 `q` double,
 `r` double,
 `pdrb` double,
 `pdrb_tanpa_migas` double,
 `triwulan` smallint(6),
 `tahun` smallint(6),
 `created_at` int(11),
 `updated_at` int(11),
 PRIMARY KEY (`id`) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `pertumbuhan_pdrb_pengeluaran_td_2010_adh_konstan_ctoc` ( 
 `id` int(11) NOT NULL AUTO_INCREMENT, 
  `a` double, 
 `b` double,
 `c` double,
 `d` double,
 `e` double,
 `f` double,
 `g` double,
 `h` double,
 `i` double,
 `j` double,
 `k` double,
 `l` double,
 `m` double,
 `o` double,
 `p` double,
 `q` double,
 `r` double,
 `pdrb` double,
 `pdrb_tanpa_migas` double,
 `triwulan` smallint(6),
 `tahun` smallint(6),
 `created_at` int(11),
 `updated_at` int(11),
 PRIMARY KEY (`id`) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `indeks_implisit` ( 
 `id` int(11) NOT NULL AUTO_INCREMENT, 
  `a` double, 
 `b` double,
 `c` double,
 `d` double,
 `e` double,
 `f` double,
 `g` double,
 `h` double,
 `i` double,
 `j` double,
 `k` double,
 `l` double,
 `m` double,
 `o` double,
 `p` double,
 `q` double,
 `r` double,
 `pdrb` double,
 `pdrb_tanpa_migas` double,
 `triwulan` smallint(6),
 `tahun` smallint(6),
 `created_at` int(11),
 `updated_at` int(11),
 PRIMARY KEY (`id`) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `laju_pertumbuhan_indeks_implisit` ( 
 `id` int(11) NOT NULL AUTO_INCREMENT, 
  `a` double, 
 `b` double,
 `c` double,
 `d` double,
 `e` double,
 `f` double,
 `g` double,
 `h` double,
 `i` double,
 `j` double,
 `k` double,
 `l` double,
 `m` double,
 `o` double,
 `p` double,
 `q` double,
 `r` double,
 `pdrb` double,
 `pdrb_tanpa_migas` double,
 `triwulan` smallint(6),
 `tahun` smallint(6),
 `created_at` int(11),
 `updated_at` int(11),
 PRIMARY KEY (`id`) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `fenomena` ( 
 `id` int(11) NOT NULL AUTO_INCREMENT, 
`a_qtoq` text,
`a_ytoy` text,
`a_laju_implisit` text,
`b_qtoq` text,
`b_ytoy` text,
`b_laju_implisit` text,
`c_qtoq` text,
`c_ytoy` text,
`c_laju_implisit` text,
`d_qtoq` text,
`d_ytoy` text,
`d_laju_implisit` text,
`e_qtoq` text,
`e_ytoy` text,
`e_laju_implisit` text,
`f_qtoq` text,
`f_ytoy` text,
`f_laju_implisit` text,
`g_qtoq` text,
`g_ytoy` text,
`g_laju_implisit` text,
`h_qtoq` text,
`h_ytoy` text,
`h_laju_implisit` text,
`i_qtoq` text,
`i_ytoy` text,
`i_laju_implisit` text,
`j_qtoq` text,
`j_ytoy` text,
`j_laju_implisit` text,
`k_qtoq` text,
`k_ytoy` text,
`k_laju_implisit` text,
`l_qtoq` text,
`l_ytoy` text,
`l_laju_implisit` text,
`m_qtoq` text,
`m_ytoy` text,
`m_laju_implisit` text,
`o_qtoq` text,
`o_ytoy` text,
`o_laju_implisit` text,
`p_qtoq` text,
`p_ytoy` text,
`p_laju_implisit` text,
`q_qtoq` text,
`q_ytoy` text,
`q_laju_implisit` text,
`r_qtoq` text,
`r_ytoy` text,
`r_laju_implisit` text,
 `id_kab` int(11),
 `triwulan` smallint(6),
 `tahun` smallint(6),
 `created_at` int(11),
 `updated_at` int(11),
 PRIMARY KEY (`id`) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `infografis` ( 
 `id` int(11) NOT NULL AUTO_INCREMENT, 
 `judul` varchar(255), 
 `keterangan` text, 
 `link` text,
 `created_at` int(11),
 `updated_at` int(11),
 PRIMARY KEY (`id`) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `tahun` ( 
 `id` int(11) NOT NULL AUTO_INCREMENT, 
 `tahun` int(4), 
 `created_at` int(11),
 `updated_at` int(11),
 PRIMARY KEY (`id`) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `judul` ( 
 `id` int(11) NOT NULL AUTO_INCREMENT, 
 `judul` text, 
 `created_at` int(11),
 `updated_at` int(11),
 PRIMARY KEY (`id`) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
 
CREATE TABLE IF NOT EXISTS `inputd` ( 
 `id` int(11) NOT NULL AUTO_INCREMENT, 
 `tahun` int(4) NOT NULL, 
 `tw` int(4) NOT NULL, 
 `judul` int(11) NOT NULL, 
 `kab` int(11) NOT NULL, 
 `prov` int(11) NOT NULL, 
 `created_at` int(11),
 `updated_at` int(11),
 PRIMARY KEY (`id`) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `kab` ( 
 `id` int(11) NOT NULL, 
 `nama` varchar(225) NOT NULL, 
 `created_at` int(11),
 `updated_at` int(11),
 PRIMARY KEY (`id`) 
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
 
 



