<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Ihp */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Ihps', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ihp-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'bahanmakanan',
            'padipalawija',
            'padi',
            'palawija',
            'jagungpocelan',
            'ketelapohon',
            'ketelarambat',
            'kacangtanah',
            'kacangkedelai',
            'kacanghijau',
            'bawangdaun',
            'bawangmerah',
            'bayam',
            'buncismuda',
            'cabemerah',
            'caberawit',
            'kacangpanjang',
            'kangkung',
            'ketimun',
            'kolkubis',
            'melinjo',
            'sawihijau',
            'terongpnjng',
            'tomat',
            'wortel',
            'kentang',
            'petai',
            'kacangmerah',
            'alpukat',
            'durian',
            'jambubiji',
            'jeruk',
            'mangga',
            'nanas',
            'pepaya',
            'pisangambon',
            'rambutan',
            'salak',
            'sawo',
            'semangka',
            'duku',
            'nangka',
            'karetgetahtebal',
            'kelapasawit',
            'kopirobusta',
            'kelapablmdikupas',
            'tebu',
            'kakao',
            'jambumete',
            'cengkeh',
            'tembakau',
            'lada',
            'ternak',
            'sapi',
            'kerbau',
            'kambing',
            'babi',
            'sususapisegar',
            'unggashasilnya',
            'ayam',
            'itik',
            'telur',
            'perikananbudidaya',
            'bandeng',
            'gurame',
            'lele',
            'mas',
            'mujair',
            'nila',
            'patin',
            'udangbudidaya',
            'rumputlaut',
            'perikanantngkap',
            'bawal',
            'cakalang',
            'kakap',
            'kembung',
            'kerapu',
            'layang',
            'selar',
            'tembang',
            'tenggiri',
            'teri',
            'tongkol',
            'udangtangkap',
            'kepiting',
            'cumicumi',
            'kayu',
            'kayujati',
            'kayurimbalainnya',
            'hasilhutan',
            'rotan',
            'bambu',
            'batubara',
            'minyakbumi',
            'gasbumidanpanasbumi',
            'bijihtembaga',
            'bijihemas',
            'batu',
            'pasir',
            'kerikil',
            'kapur',
            'dagingsapi',
            'dagingayam',
            'dagingbabi',
            'dagingkambingdomba',
            'dagingolahanawetan',
            'ikanbekuawetan',
            'udangbekuawetan',
            'minyakkelapa',
            'minyakgoreng',
            'minyakkelapasawit',
            'sususegar',
            'susukentalmanis',
            'susububuk',
            'susucairkemasan',
            'eskrim',
            'makanandarisusu',
            'beras',
            'tepungterigu',
            'tepungtapioka',
            'tepungberas',
            'tepunglainnya',
            'pakanikan',
            'pakanlain',
            'roti',
            'biskuit',
            'mie',
            'gulapasir',
            'gulamerah',
            'sirop',
            'kembanggula',
            'coklatbubuk',
            'kopibubuk',
            'teh',
            'kecap',
            'tahutempe',
            'garammeja',
            'kerupukkeripik',
            'airminumkemasan',
            'minumanringan',
            'tehkemasan',
            'rokokkretek',
            'rokokfilter',
            'benangpintal',
            'benangrayon',
            'benangpolyester',
            'kaintenun',
            'kaincetak',
            'lainnya',
            'pakaianbatik',
            'pakaiandarikaos',
            'pakaianpria',
            'pakaianwanita',
            'pakaiananakanak',
            'perlengkapanpakaian',
            'sepatudewasa',
            'sandaldewasa',
            'sepatusandalanakanak',
            'sepatuolahraga',
            'kayujatigergajian',
            'kayulainnya',
            'bahanbangunankayu',
            'kertaskoran',
            'kertastulis',
            'tissue',
            'kertaspembungkus',
            'karton',
            'kartonkemasan',
            'pupukurea',
            'pupuklainnya',
            'pestisidainsektisida',
            'bijiplastik',
            'bahankimia',
            'cattembok',
            'catkayubesi',
            'vernislak',
            'deterjen',
            'sabunmandi',
            'pemutihpewangi',
            'kosmetik',
            'bahankimialain',
            'premium',
            'avtur',
            'solar',
            'aspal',
            'minyakpelumas',
            'rss',
            'sir',
            'banmobil',
            'bansepedamotor',
            'vulkanisirban',
            'pvc',
            'plastik',
            'barangkaretdanplastiklain',
            'kacalembaran',
            'keramik',
            'barangpecahbelah',
            'batubata',
            'genteng',
            'semen',
            'conblock',
            'barangbukanlogamlainnya',
            'bajalembaran',
            'besibeton',
            'besisiku',
            'besiplat',
            'pipabesi',
            'alumunium',
            'seng',
            'murpakubaut',
            'kawat',
            'lainnyadarilogam',
            'mesinpembangkit',
            'mesinindustri',
            'mesinpertanian',
            'alatberat',
            'kabellistrik',
            'prlngkapanlistrik',
            'komputer',
            'televisi',
            'elektroniklainnya',
            'teleponhp',
            'mobil',
            'kapaldanperbaikan',
            'sparepart1',
            'sepedamotor',
            'sparepart2',
            'lainnyaanguktan',
            'furniturekayu',
            'furniturerotan',
            'furniturelogam',
            'barangindustrilainnya',
            'fenomena:ntext',
            'id_satuan',
            'id_tahun',
            'id_tw',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>
