<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\Ihpb;

/**
 * Ihpbsearch represents the model behind the search form about `app\models\Ihpb`.
 */
class Ihpbsearch extends Ihpb
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'id_tw', 'id_satuan', 'id_tahun', 'created_at', 'updated_at'], 'integer'],
            [['tomat', 'kubiskol', 'daunbawang', 'sawi', 'kacangpanjang', 'wortel', 'buncis', 'mentimun', 'terung', 'kangkung', 'bayam', 'semangka', 'melon', 'kacangtanah', 'kedelai', 'ketelapohon', 'ubijalar', 'kentang', 'kacanghijau', 'tebu', 'tanamanbunga', 'tembakau', 'kapuk', 'pertniantnamanthunan', 'cabemerah', 'caberawit', 'jeruk', 'mangga', 'salak', 'pisang', 'apellokal', 'rambutan', 'pepaya', 'alpukat', 'jambubiji', 'sawo', 'nanas', 'jambumete', 'kelapasawit', 'kelapa', 'kopi', 'lada', 'kakao', 'cengkeh', 'teh', 'karet', 'tnamanbiofarmaka', 'peternakan', 'ayamras', 'sapi', 'ayamburas', 'kambingdandomba', 'kerbau', 'babi', 'itik', 'sususegar', 'telurayamburas', 'teluritik', 'telurayamras', 'pengusahaanhutan', 'meranti', 'kayujatigelondongan', 'kruing', 'rotan', 'perikanantangkap', 'bawal', 'tenggiri', 'tongkol', 'kakapputih', 'kakapmerahbambangan', 'kembung', 'cakalang', 'kerapu', 'layang', 'selar', 'teri', 'tuna', 'kepitingairlaut', 'udangairtawar', 'udanglaut', 'cumicumi', 'manyung', 'perikananbudidaya', 'patin', 'lele', 'nila', 'ikanmas', 'bandeng', 'gurami', 'gabus', 'rumputlaut', 'pertmbanganbatubara', 'batubara', 'penggalianbatupasirdantanahliat', 'batuhiasdanbatubangunan', 'batubahanindustri', 'tanahdantanahliat', 'pasir', 'kerikil', 'pertpenggalian', 'barangtambangmineralbknlogam', 'penggalianlainnya', 'industripengolahandanpengawetandaging', 'dagingsapi', 'dagingkambing', 'dagingbabi', 'dagingayam', 'dagingdlamkaleng', 'dagingolahan', 'industripengolahandanpengawetanikan', 'ikanteriasinkering', 'ikanasinkeringlainnya', 'ikanbeku', 'industripengolahandanpengawetanbuah', 'buahdansayurkalengan', 'buahdansayurlumatan', 'tempe', 'tahu', 'inyakkelapasawit', 'margarine', 'minyakgorengkelapa', 'minyakgorengkelapasawit', 'kopra', 'industripengolahansusu', 'susucair', 'susububuk', 'susukental', 'eskrim', 'industripenggilinganpadi', 'beras', 'tepungterigu', 'tepungberas', 'tepungtapioka', 'kopibijikupasan', 'coklatbijikupasan', 'industrimknnlainnya', 'roti', 'biskuit', 'wafer', 'gulapasir', 'gulamerah', 'sirop', 'bubukcoklat', 'coklatolahan', 'kembanggula', 'kecap', 'miekering', 'kerupuk', 'mieinstan', 'vermicellibihun', 'bumbumsakdanpnyedap', 'soun', 'tehhijau', 'tehhitam', 'santankelapa', 'natadecoco', 'tehekstrak', 'kopibijimatang', 'mkanandarikacang', 'kopibubuk', 'kopiinstan', 'industrimakananhewan', 'mknantrnakbesardanunggas', 'mkananikan', 'industriminuman', 'minumanberalkohol', 'minumanringanco2', 'airdngnaromabuah', 'airdngnaromateh', 'airmineral', 'industripengolahantembakau', 'tembakauolahan', 'rokokkretek', 'rokokputih', 'industripemintalan', 'benang', 'kaintenun', 'kaincetak', 'kainbatik', 'industritekstillainnya', 'permadani', 'industripakaianjadi', 'rajutan', 'pakaianpriabatik', 'pakaianprianonbatik', 'pakaianwanitabatik', 'pakaianwanitanonbatik', 'pakaiandalampria', 'pakaiandalamwanita', 'pakaianolahraga', 'perlengkapanpakaian', 'industrikulit', 'kulit', 'brangbrangdarikulit', 'industrialaskaki', 'sepatu', 'sandal', 'sepatuolahraga', 'industripenggergajian', 'kayujatigergajian', 'kayurimbagergajian', 'industribrangdarikayu', 'kayulapis', 'mouldingdowel', 'bahanbangunankayu', 'brngterbuatdarikayugabusbamburotan', 'anyamanrotan', 'anyamanbambu', 'anyamanlainnya', 'industrikertas', 'kertaskoran', 'kertastulis', 'kertaskonstruksi', 'tissue', 'brngbrngdarikertas', 'industripercetakan', 'barangcetakan', 'industriprodukpengilngnmnyakbumi', 'avgas', 'avtur', 'premium', 'minyaktanah', 'solar', 'minyakdiesel', 'minyakbakar', 'minyakpelumas', 'aspal', 'lpg', 'industribahankimia', 'kimiadasarorganik', 'kimiadasaranorganik', 'pupukurea', 'pupukalam', 'pupuknpk', 'damarbuatan', 'lateksbuatan', 'industribahankimialainnya', 'pestisidauntkpertniandanindustri', 'insektisidauntkrmhtngga', 'catkayubesi', 'cattembok', 'pernisdempuldanthinner', 'tintacetak', 'sabun', 'pembersihlantaiklosetdanlainnya', 'pastagigi', 'pemutih', 'brngbrngkosmetik', 'barangkimialainnya', 'industrifarmasi', 'produkfarmasi', 'jamu', 'industrikaret', 'banluarmobildantruk', 'banluarsepedamotor', 'banluarsepeda', 'bandalammobildantruk', 'bandalamsepedamotor', 'bandalamsepeda', 'karetasap', 'karetremilling', 'karetremah', 'brngkperlanrmhtnggadarikaret', 'brngkperluanindustridarikaret', 'industribrngdariplstik', 'pipapvc', 'pipaplstikselainpvc', 'selang', 'plstiklembaran', 'kmsandariplastik', 'prlengkpnrmhtnggadariplastik', 'industrikacadanbrngdarikaa', 'prlengkpnrmhtnggadariporselindatanahliat', 'klosetwastafeldansejenisnya', 'keramiklantai', 'batubata', 'genteng', 'semenportland', 'semenlainnya', 'batusplit', 'readymix', 'konblok', 'batako', 'pipabeton', 'tiangbeton', 'gentengsemen', 'bhnbngunandarimarmergranitdansejenis', 'industrilogamdasarbejidanbaja', 'billetbaja', 'besibeton', 'besiprofil', 'bajalembaran', 'besipipa', 'besiplat', 'kawatbeton', 'kawatlainnya', 'industrilogamdasarmulia', 'alumunium', 'timah', 'seng', 'industribaranglogamsiappasang', 'tangki', 'bahanbangunanalumunium', 'bahanbangunanbaja', 'bahanbangunansiappasanglogam', 'industribaranglogamlainnya', 'pakumurbaut', 'kalengdrum', 'alatdapurdanpertaniandarilogam', 'perabotrumahtanggadankantordarilogam', 'industrikomputerdanperlengkapan', 'komputerdanperlengkapannya', 'industriperalatanaudiodanvideo', 'pemutardvdvcd', 'industrialatukuralatuji', 'alatukur', 'arlojidanjam', 'industriperalatanfotografi', 'kameradanperlengkapannya', 'teropongdanperlengkapannya', 'industrimediamagnetik', 'mediamagnetikdanmediaoptik', 'industrimotorlistrik', 'mesinlistrik', 'industribatubaterai', 'batubaterai', 'aki', 'industrikabeldanperlengkapannya', 'perlengkapanlistrik', 'industriperalatanrumahtangga', 'mesincuci', 'lemaries', 'televisi', 'industrimesinkeperluanumum', 'perkakastangan', 'mesinpembungkuspembotolan', 'mesinpendinginindustri', 'industrimesinkeperluankhusus', 'mesinpertaniandankehutanan', 'mesinpengolahlogam', 'alatalatberat', 'industrikendaraanbermotorrodaempat', 'busdantruk', 'mobil', 'industrisukucadangdanaksesori', 'sukucdngkendaraanbermotorrodaempat', 'industrialatangkutanlainnya', 'sepeda', 'sukucadangsepeda', 'sepedamotor', 'sukucadangsepedamotor', 'industrifurnitur', 'furniturdarikayu', 'furniturdarirotanbambu', 'furniturlainnya', 'industribarangperhiasan', 'perhiasanemas', 'perhiasanperak', 'industrialatmusik', 'alatmusik', 'industrialatolahraga', 'boladanshuttlecock', 'raketdannet', 'industriperalatankedokteran', 'alatalatkedokteran', 'kacamatadanlensa'], 'number'],
            [['fenomena'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Ihpb::find();

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
            'tomat' => $this->tomat,
            'kubiskol' => $this->kubiskol,
            'daunbawang' => $this->daunbawang,
            'sawi' => $this->sawi,
            'kacangpanjang' => $this->kacangpanjang,
            'wortel' => $this->wortel,
            'buncis' => $this->buncis,
            'mentimun' => $this->mentimun,
            'terung' => $this->terung,
            'kangkung' => $this->kangkung,
            'bayam' => $this->bayam,
            'semangka' => $this->semangka,
            'melon' => $this->melon,
            'kacangtanah' => $this->kacangtanah,
            'kedelai' => $this->kedelai,
            'ketelapohon' => $this->ketelapohon,
            'ubijalar' => $this->ubijalar,
            'kentang' => $this->kentang,
            'kacanghijau' => $this->kacanghijau,
            'tebu' => $this->tebu,
            'tanamanbunga' => $this->tanamanbunga,
            'tembakau' => $this->tembakau,
            'kapuk' => $this->kapuk,
            'pertniantnamanthunan' => $this->pertniantnamanthunan,
            'cabemerah' => $this->cabemerah,
            'caberawit' => $this->caberawit,
            'jeruk' => $this->jeruk,
            'mangga' => $this->mangga,
            'salak' => $this->salak,
            'pisang' => $this->pisang,
            'apellokal' => $this->apellokal,
            'rambutan' => $this->rambutan,
            'pepaya' => $this->pepaya,
            'alpukat' => $this->alpukat,
            'jambubiji' => $this->jambubiji,
            'sawo' => $this->sawo,
            'nanas' => $this->nanas,
            'jambumete' => $this->jambumete,
            'kelapasawit' => $this->kelapasawit,
            'kelapa' => $this->kelapa,
            'kopi' => $this->kopi,
            'lada' => $this->lada,
            'kakao' => $this->kakao,
            'cengkeh' => $this->cengkeh,
            'teh' => $this->teh,
            'karet' => $this->karet,
            'tnamanbiofarmaka' => $this->tnamanbiofarmaka,
            'peternakan' => $this->peternakan,
            'ayamras' => $this->ayamras,
            'sapi' => $this->sapi,
            'ayamburas' => $this->ayamburas,
            'kambingdandomba' => $this->kambingdandomba,
            'kerbau' => $this->kerbau,
            'babi' => $this->babi,
            'itik' => $this->itik,
            'sususegar' => $this->sususegar,
            'telurayamburas' => $this->telurayamburas,
            'teluritik' => $this->teluritik,
            'telurayamras' => $this->telurayamras,
            'pengusahaanhutan' => $this->pengusahaanhutan,
            'meranti' => $this->meranti,
            'kayujatigelondongan' => $this->kayujatigelondongan,
            'kruing' => $this->kruing,
            'rotan' => $this->rotan,
            'perikanantangkap' => $this->perikanantangkap,
            'bawal' => $this->bawal,
            'tenggiri' => $this->tenggiri,
            'tongkol' => $this->tongkol,
            'kakapputih' => $this->kakapputih,
            'kakapmerahbambangan' => $this->kakapmerahbambangan,
            'kembung' => $this->kembung,
            'cakalang' => $this->cakalang,
            'kerapu' => $this->kerapu,
            'layang' => $this->layang,
            'selar' => $this->selar,
            'teri' => $this->teri,
            'tuna' => $this->tuna,
            'kepitingairlaut' => $this->kepitingairlaut,
            'udangairtawar' => $this->udangairtawar,
            'udanglaut' => $this->udanglaut,
            'cumicumi' => $this->cumicumi,
            'manyung' => $this->manyung,
            'perikananbudidaya' => $this->perikananbudidaya,
            'patin' => $this->patin,
            'lele' => $this->lele,
            'nila' => $this->nila,
            'ikanmas' => $this->ikanmas,
            'bandeng' => $this->bandeng,
            'gurami' => $this->gurami,
            'gabus' => $this->gabus,
            'rumputlaut' => $this->rumputlaut,
            'pertmbanganbatubara' => $this->pertmbanganbatubara,
            'batubara' => $this->batubara,
            'penggalianbatupasirdantanahliat' => $this->penggalianbatupasirdantanahliat,
            'batuhiasdanbatubangunan' => $this->batuhiasdanbatubangunan,
            'batubahanindustri' => $this->batubahanindustri,
            'tanahdantanahliat' => $this->tanahdantanahliat,
            'pasir' => $this->pasir,
            'kerikil' => $this->kerikil,
            'pertpenggalian' => $this->pertpenggalian,
            'barangtambangmineralbknlogam' => $this->barangtambangmineralbknlogam,
            'penggalianlainnya' => $this->penggalianlainnya,
            'industripengolahandanpengawetandaging' => $this->industripengolahandanpengawetandaging,
            'dagingsapi' => $this->dagingsapi,
            'dagingkambing' => $this->dagingkambing,
            'dagingbabi' => $this->dagingbabi,
            'dagingayam' => $this->dagingayam,
            'dagingdlamkaleng' => $this->dagingdlamkaleng,
            'dagingolahan' => $this->dagingolahan,
            'industripengolahandanpengawetanikan' => $this->industripengolahandanpengawetanikan,
            'ikanteriasinkering' => $this->ikanteriasinkering,
            'ikanasinkeringlainnya' => $this->ikanasinkeringlainnya,
            'ikanbeku' => $this->ikanbeku,
            'industripengolahandanpengawetanbuah' => $this->industripengolahandanpengawetanbuah,
            'buahdansayurkalengan' => $this->buahdansayurkalengan,
            'buahdansayurlumatan' => $this->buahdansayurlumatan,
            'tempe' => $this->tempe,
            'tahu' => $this->tahu,
            'inyakkelapasawit' => $this->inyakkelapasawit,
            'margarine' => $this->margarine,
            'minyakgorengkelapa' => $this->minyakgorengkelapa,
            'minyakgorengkelapasawit' => $this->minyakgorengkelapasawit,
            'kopra' => $this->kopra,
            'industripengolahansusu' => $this->industripengolahansusu,
            'susucair' => $this->susucair,
            'susububuk' => $this->susububuk,
            'susukental' => $this->susukental,
            'eskrim' => $this->eskrim,
            'industripenggilinganpadi' => $this->industripenggilinganpadi,
            'beras' => $this->beras,
            'tepungterigu' => $this->tepungterigu,
            'tepungberas' => $this->tepungberas,
            'tepungtapioka' => $this->tepungtapioka,
            'kopibijikupasan' => $this->kopibijikupasan,
            'coklatbijikupasan' => $this->coklatbijikupasan,
            'industrimknnlainnya' => $this->industrimknnlainnya,
            'roti' => $this->roti,
            'biskuit' => $this->biskuit,
            'wafer' => $this->wafer,
            'gulapasir' => $this->gulapasir,
            'gulamerah' => $this->gulamerah,
            'sirop' => $this->sirop,
            'bubukcoklat' => $this->bubukcoklat,
            'coklatolahan' => $this->coklatolahan,
            'kembanggula' => $this->kembanggula,
            'kecap' => $this->kecap,
            'miekering' => $this->miekering,
            'kerupuk' => $this->kerupuk,
            'mieinstan' => $this->mieinstan,
            'vermicellibihun' => $this->vermicellibihun,
            'bumbumsakdanpnyedap' => $this->bumbumsakdanpnyedap,
            'soun' => $this->soun,
            'tehhijau' => $this->tehhijau,
            'tehhitam' => $this->tehhitam,
            'santankelapa' => $this->santankelapa,
            'natadecoco' => $this->natadecoco,
            'tehekstrak' => $this->tehekstrak,
            'kopibijimatang' => $this->kopibijimatang,
            'mkanandarikacang' => $this->mkanandarikacang,
            'kopibubuk' => $this->kopibubuk,
            'kopiinstan' => $this->kopiinstan,
            'industrimakananhewan' => $this->industrimakananhewan,
            'mknantrnakbesardanunggas' => $this->mknantrnakbesardanunggas,
            'mkananikan' => $this->mkananikan,
            'industriminuman' => $this->industriminuman,
            'minumanberalkohol' => $this->minumanberalkohol,
            'minumanringanco2' => $this->minumanringanco2,
            'airdngnaromabuah' => $this->airdngnaromabuah,
            'airdngnaromateh' => $this->airdngnaromateh,
            'airmineral' => $this->airmineral,
            'industripengolahantembakau' => $this->industripengolahantembakau,
            'tembakauolahan' => $this->tembakauolahan,
            'rokokkretek' => $this->rokokkretek,
            'rokokputih' => $this->rokokputih,
            'industripemintalan' => $this->industripemintalan,
            'benang' => $this->benang,
            'kaintenun' => $this->kaintenun,
            'kaincetak' => $this->kaincetak,
            'kainbatik' => $this->kainbatik,
            'industritekstillainnya' => $this->industritekstillainnya,
            'permadani' => $this->permadani,
            'industripakaianjadi' => $this->industripakaianjadi,
            'rajutan' => $this->rajutan,
            'pakaianpriabatik' => $this->pakaianpriabatik,
            'pakaianprianonbatik' => $this->pakaianprianonbatik,
            'pakaianwanitabatik' => $this->pakaianwanitabatik,
            'pakaianwanitanonbatik' => $this->pakaianwanitanonbatik,
            'pakaiandalampria' => $this->pakaiandalampria,
            'pakaiandalamwanita' => $this->pakaiandalamwanita,
            'pakaianolahraga' => $this->pakaianolahraga,
            'perlengkapanpakaian' => $this->perlengkapanpakaian,
            'industrikulit' => $this->industrikulit,
            'kulit' => $this->kulit,
            'brangbrangdarikulit' => $this->brangbrangdarikulit,
            'industrialaskaki' => $this->industrialaskaki,
            'sepatu' => $this->sepatu,
            'sandal' => $this->sandal,
            'sepatuolahraga' => $this->sepatuolahraga,
            'industripenggergajian' => $this->industripenggergajian,
            'kayujatigergajian' => $this->kayujatigergajian,
            'kayurimbagergajian' => $this->kayurimbagergajian,
            'industribrangdarikayu' => $this->industribrangdarikayu,
            'kayulapis' => $this->kayulapis,
            'mouldingdowel' => $this->mouldingdowel,
            'bahanbangunankayu' => $this->bahanbangunankayu,
            'brngterbuatdarikayugabusbamburotan' => $this->brngterbuatdarikayugabusbamburotan,
            'anyamanrotan' => $this->anyamanrotan,
            'anyamanbambu' => $this->anyamanbambu,
            'anyamanlainnya' => $this->anyamanlainnya,
            'industrikertas' => $this->industrikertas,
            'kertaskoran' => $this->kertaskoran,
            'kertastulis' => $this->kertastulis,
            'kertaskonstruksi' => $this->kertaskonstruksi,
            'tissue' => $this->tissue,
            'brngbrngdarikertas' => $this->brngbrngdarikertas,
            'industripercetakan' => $this->industripercetakan,
            'barangcetakan' => $this->barangcetakan,
            'industriprodukpengilngnmnyakbumi' => $this->industriprodukpengilngnmnyakbumi,
            'avgas' => $this->avgas,
            'avtur' => $this->avtur,
            'premium' => $this->premium,
            'minyaktanah' => $this->minyaktanah,
            'solar' => $this->solar,
            'minyakdiesel' => $this->minyakdiesel,
            'minyakbakar' => $this->minyakbakar,
            'minyakpelumas' => $this->minyakpelumas,
            'aspal' => $this->aspal,
            'lpg' => $this->lpg,
            'industribahankimia' => $this->industribahankimia,
            'kimiadasarorganik' => $this->kimiadasarorganik,
            'kimiadasaranorganik' => $this->kimiadasaranorganik,
            'pupukurea' => $this->pupukurea,
            'pupukalam' => $this->pupukalam,
            'pupuknpk' => $this->pupuknpk,
            'damarbuatan' => $this->damarbuatan,
            'lateksbuatan' => $this->lateksbuatan,
            'industribahankimialainnya' => $this->industribahankimialainnya,
            'pestisidauntkpertniandanindustri' => $this->pestisidauntkpertniandanindustri,
            'insektisidauntkrmhtngga' => $this->insektisidauntkrmhtngga,
            'catkayubesi' => $this->catkayubesi,
            'cattembok' => $this->cattembok,
            'pernisdempuldanthinner' => $this->pernisdempuldanthinner,
            'tintacetak' => $this->tintacetak,
            'sabun' => $this->sabun,
            'pembersihlantaiklosetdanlainnya' => $this->pembersihlantaiklosetdanlainnya,
            'pastagigi' => $this->pastagigi,
            'pemutih' => $this->pemutih,
            'brngbrngkosmetik' => $this->brngbrngkosmetik,
            'barangkimialainnya' => $this->barangkimialainnya,
            'industrifarmasi' => $this->industrifarmasi,
            'produkfarmasi' => $this->produkfarmasi,
            'jamu' => $this->jamu,
            'industrikaret' => $this->industrikaret,
            'banluarmobildantruk' => $this->banluarmobildantruk,
            'banluarsepedamotor' => $this->banluarsepedamotor,
            'banluarsepeda' => $this->banluarsepeda,
            'bandalammobildantruk' => $this->bandalammobildantruk,
            'bandalamsepedamotor' => $this->bandalamsepedamotor,
            'bandalamsepeda' => $this->bandalamsepeda,
            'karetasap' => $this->karetasap,
            'karetremilling' => $this->karetremilling,
            'karetremah' => $this->karetremah,
            'brngkperlanrmhtnggadarikaret' => $this->brngkperlanrmhtnggadarikaret,
            'brngkperluanindustridarikaret' => $this->brngkperluanindustridarikaret,
            'industribrngdariplstik' => $this->industribrngdariplstik,
            'pipapvc' => $this->pipapvc,
            'pipaplstikselainpvc' => $this->pipaplstikselainpvc,
            'selang' => $this->selang,
            'plstiklembaran' => $this->plstiklembaran,
            'kmsandariplastik' => $this->kmsandariplastik,
            'prlengkpnrmhtnggadariplastik' => $this->prlengkpnrmhtnggadariplastik,
            'industrikacadanbrngdarikaa' => $this->industrikacadanbrngdarikaa,
            'prlengkpnrmhtnggadariporselindatanahliat' => $this->prlengkpnrmhtnggadariporselindatanahliat,
            'klosetwastafeldansejenisnya' => $this->klosetwastafeldansejenisnya,
            'keramiklantai' => $this->keramiklantai,
            'batubata' => $this->batubata,
            'genteng' => $this->genteng,
            'semenportland' => $this->semenportland,
            'semenlainnya' => $this->semenlainnya,
            'batusplit' => $this->batusplit,
            'readymix' => $this->readymix,
            'konblok' => $this->konblok,
            'batako' => $this->batako,
            'pipabeton' => $this->pipabeton,
            'tiangbeton' => $this->tiangbeton,
            'gentengsemen' => $this->gentengsemen,
            'bhnbngunandarimarmergranitdansejenis' => $this->bhnbngunandarimarmergranitdansejenis,
            'industrilogamdasarbejidanbaja' => $this->industrilogamdasarbejidanbaja,
            'billetbaja' => $this->billetbaja,
            'besibeton' => $this->besibeton,
            'besiprofil' => $this->besiprofil,
            'bajalembaran' => $this->bajalembaran,
            'besipipa' => $this->besipipa,
            'besiplat' => $this->besiplat,
            'kawatbeton' => $this->kawatbeton,
            'kawatlainnya' => $this->kawatlainnya,
            'industrilogamdasarmulia' => $this->industrilogamdasarmulia,
            'alumunium' => $this->alumunium,
            'timah' => $this->timah,
            'seng' => $this->seng,
            'industribaranglogamsiappasang' => $this->industribaranglogamsiappasang,
            'tangki' => $this->tangki,
            'bahanbangunanalumunium' => $this->bahanbangunanalumunium,
            'bahanbangunanbaja' => $this->bahanbangunanbaja,
            'bahanbangunansiappasanglogam' => $this->bahanbangunansiappasanglogam,
            'industribaranglogamlainnya' => $this->industribaranglogamlainnya,
            'pakumurbaut' => $this->pakumurbaut,
            'kalengdrum' => $this->kalengdrum,
            'alatdapurdanpertaniandarilogam' => $this->alatdapurdanpertaniandarilogam,
            'perabotrumahtanggadankantordarilogam' => $this->perabotrumahtanggadankantordarilogam,
            'industrikomputerdanperlengkapan' => $this->industrikomputerdanperlengkapan,
            'komputerdanperlengkapannya' => $this->komputerdanperlengkapannya,
            'industriperalatanaudiodanvideo' => $this->industriperalatanaudiodanvideo,
            'pemutardvdvcd' => $this->pemutardvdvcd,
            'industrialatukuralatuji' => $this->industrialatukuralatuji,
            'alatukur' => $this->alatukur,
            'arlojidanjam' => $this->arlojidanjam,
            'industriperalatanfotografi' => $this->industriperalatanfotografi,
            'kameradanperlengkapannya' => $this->kameradanperlengkapannya,
            'teropongdanperlengkapannya' => $this->teropongdanperlengkapannya,
            'industrimediamagnetik' => $this->industrimediamagnetik,
            'mediamagnetikdanmediaoptik' => $this->mediamagnetikdanmediaoptik,
            'industrimotorlistrik' => $this->industrimotorlistrik,
            'mesinlistrik' => $this->mesinlistrik,
            'industribatubaterai' => $this->industribatubaterai,
            'batubaterai' => $this->batubaterai,
            'aki' => $this->aki,
            'industrikabeldanperlengkapannya' => $this->industrikabeldanperlengkapannya,
            'perlengkapanlistrik' => $this->perlengkapanlistrik,
            'industriperalatanrumahtangga' => $this->industriperalatanrumahtangga,
            'mesincuci' => $this->mesincuci,
            'lemaries' => $this->lemaries,
            'televisi' => $this->televisi,
            'industrimesinkeperluanumum' => $this->industrimesinkeperluanumum,
            'perkakastangan' => $this->perkakastangan,
            'mesinpembungkuspembotolan' => $this->mesinpembungkuspembotolan,
            'mesinpendinginindustri' => $this->mesinpendinginindustri,
            'industrimesinkeperluankhusus' => $this->industrimesinkeperluankhusus,
            'mesinpertaniandankehutanan' => $this->mesinpertaniandankehutanan,
            'mesinpengolahlogam' => $this->mesinpengolahlogam,
            'alatalatberat' => $this->alatalatberat,
            'industrikendaraanbermotorrodaempat' => $this->industrikendaraanbermotorrodaempat,
            'busdantruk' => $this->busdantruk,
            'mobil' => $this->mobil,
            'industrisukucadangdanaksesori' => $this->industrisukucadangdanaksesori,
            'sukucdngkendaraanbermotorrodaempat' => $this->sukucdngkendaraanbermotorrodaempat,
            'industrialatangkutanlainnya' => $this->industrialatangkutanlainnya,
            'sepeda' => $this->sepeda,
            'sukucadangsepeda' => $this->sukucadangsepeda,
            'sepedamotor' => $this->sepedamotor,
            'sukucadangsepedamotor' => $this->sukucadangsepedamotor,
            'industrifurnitur' => $this->industrifurnitur,
            'furniturdarikayu' => $this->furniturdarikayu,
            'furniturdarirotanbambu' => $this->furniturdarirotanbambu,
            'furniturlainnya' => $this->furniturlainnya,
            'industribarangperhiasan' => $this->industribarangperhiasan,
            'perhiasanemas' => $this->perhiasanemas,
            'perhiasanperak' => $this->perhiasanperak,
            'industrialatmusik' => $this->industrialatmusik,
            'alatmusik' => $this->alatmusik,
            'industrialatolahraga' => $this->industrialatolahraga,
            'boladanshuttlecock' => $this->boladanshuttlecock,
            'raketdannet' => $this->raketdannet,
            'industriperalatankedokteran' => $this->industriperalatankedokteran,
            'alatalatkedokteran' => $this->alatalatkedokteran,
            'kacamatadanlensa' => $this->kacamatadanlensa,
            'id_tw' => $this->id_tw,
            'id_satuan' => $this->id_satuan,
            'id_tahun' => $this->id_tahun,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ]);

        $query->andFilterWhere(['like', 'fenomena', $this->fenomena]);

        return $dataProvider;
    }
}
